/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * form_spesifikasi.java
 *
 * Created on Jan 14, 2020, 7:12:35 PM
 */
package approval_app;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Conek;

/**
 *
 * @author assar
 */
public class form_spesifikasi extends javax.swing.JFrame {

    /**
     * Creates new form form_spesifikasi
     */
    public form_spesifikasi() {
        initComponents();
        model = new DefaultTableModel();
        tblSpek.setModel(model);
        model.addColumn("Ing Class");
        model.addColumn("Code");
        model.addColumn("Ingredient");
        model.addColumn("Qty");

        tampil_combo_inclass();
        getData();
        this.setLocationRelativeTo(null);
    }

    private final DefaultTableModel model;
    private void kosong(){
        txtCode.setText(null);
        txtIngred.setText(null);
        txtQty.setText(null);
        txtMin.setText(null);
        txtMax.setText(null);
        
    }
    public void getData() {
        try {
            Statement stat = (Statement) Conek.GetConnection().createStatement();
            String sql = "SELECT ingredient.name_IS as name_IS, material.kode_mt as kode_mt, material.deskripsi as deskripsi, detail_spec.qty as qty FROM `tb_spesifikasi` as spec left join tb_detail_spesifikasi as detail_spec on spec.kode_S = detail_spec.kode_S left join tb_ing_class as ingredient on detail_spec.kode_IS = ingredient.kode_IS LEFT JOIN tb_material as material on detail_spec.kode_mt = material.kode_mt";
            ResultSet res = stat.executeQuery(sql);

            while (res.next()) {
                Object[] obj = new Object[4];
                obj[0] = res.getString("name_IS");
                obj[1] = res.getString("kode_mt");
                obj[2] = res.getString("deskripsi");
                obj[3] = res.getInt("qty");
                model.addRow(obj);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Not Tampil");
        }
    }

    public void tampil_combo_inclass() {
        try {
            String query = "SELECT * FROM tb_ing_class";
            Connection konek = Conek.GetConnection();
            Statement stmt = konek.createStatement();
            ResultSet result = stmt.executeQuery(query);

            while (result.next()) {
                Vector model = new Vector();
                model.addElement(new Item(result.getInt("kode_IS"), result.getString("name_IS")));
                comboIngClass.addItem(result.getString("name_IS"));
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelCompound = new javax.swing.JLabel();
        labelDeskripsi = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtCode = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        labelIngclass = new javax.swing.JLabel();
        labelCode = new javax.swing.JLabel();
        labelDeskripsiTextfield = new javax.swing.JLabel();
        labelQty = new javax.swing.JLabel();
        labelToleransi = new javax.swing.JLabel();
        labelMin = new javax.swing.JLabel();
        labelMax = new javax.swing.JLabel();
        labelTemp = new javax.swing.JLabel();
        labelRamPress = new javax.swing.JLabel();
        labelRotorSpeed = new javax.swing.JLabel();
        labelStandard = new javax.swing.JLabel();
        kodeSpek = new javax.swing.JTextField();
        labelKodeSpek = new javax.swing.JLabel();
        txtIngred = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        txtMax = new javax.swing.JTextField();
        jTextField136 = new javax.swing.JTextField();
        jTextField137 = new javax.swing.JTextField();
        jTextField138 = new javax.swing.JTextField();
        panelTTD = new javax.swing.JPanel();
        txtTemp = new javax.swing.JTextField();
        txtRamPress = new javax.swing.JTextField();
        txtRotor = new javax.swing.JTextField();
        labelTgl = new javax.swing.JLabel();
        labelRevisi = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtRevisi = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        chkStaff = new javax.swing.JCheckBox();
        chkSH = new javax.swing.JCheckBox();
        chkADH = new javax.swing.JCheckBox();
        chkDH = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        ttdStaff = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        ttdStaff2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        ttdSH = new javax.swing.JTextPane();
        labelTtdSH = new javax.swing.JLabel();
        labelTtdSH1 = new javax.swing.JLabel();
        labelTtdSH2 = new javax.swing.JLabel();
        labelTtdSH3 = new javax.swing.JLabel();
        btnAddInput = new javax.swing.JButton();
        comboIngClass = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSpek = new javax.swing.JTable();
        btnEditInput = new javax.swing.JButton();
        btnEditInput1 = new javax.swing.JButton();
        btnClearInput = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jTextField87 = new javax.swing.JTextField();
        jTextField88 = new javax.swing.JTextField();
        jTextField89 = new javax.swing.JTextField();
        jTextField90 = new javax.swing.JTextField();
        jTextField91 = new javax.swing.JTextField();
        jTextField92 = new javax.swing.JTextField();
        jTextField93 = new javax.swing.JTextField();
        jTextField94 = new javax.swing.JTextField();
        jTextField95 = new javax.swing.JTextField();
        jTextField96 = new javax.swing.JTextField();
        jTextField97 = new javax.swing.JTextField();
        jTextField98 = new javax.swing.JTextField();
        jTextField99 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField100 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1500, 2000));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 1029));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        labelCompound.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        labelCompound.setForeground(new java.awt.Color(255, 255, 255));
        labelCompound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompound.setText("Kode Compound");

        labelDeskripsi.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        labelDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        labelDeskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDeskripsi.setText("Deskripsi");

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));

        txtCode.setBackground(new java.awt.Color(204, 204, 204));
        txtCode.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtCode.setForeground(new java.awt.Color(255, 255, 255));
        txtCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jPanel5.setBackground(new java.awt.Color(0, 255, 204));

        labelIngclass.setFont(new java.awt.Font("Tekton Pro", 1, 15)); // NOI18N
        labelIngclass.setText("Ing. Class");

        labelCode.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelCode.setText("Code");

        labelDeskripsiTextfield.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelDeskripsiTextfield.setText("Deskripsi");

        labelQty.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelQty.setText("QTY");

        labelToleransi.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelToleransi.setText("Tolerance");

        labelMin.setFont(new java.awt.Font("Tekton Pro", 1, 15)); // NOI18N
        labelMin.setText("Min");

        labelMax.setFont(new java.awt.Font("Tekton Pro", 1, 15)); // NOI18N
        labelMax.setText("Max");

        labelTemp.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelTemp.setText("Temperature");

        labelRamPress.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelRamPress.setText("Ram press");

        labelRotorSpeed.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelRotorSpeed.setText("Rotor Speed");

        labelStandard.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelStandard.setText("Standard");

        labelKodeSpek.setText("Kode Spek");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelKodeSpek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kodeSpek, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelIngclass)
                        .addGap(28, 28, 28)
                        .addComponent(labelCode)
                        .addGap(42, 42, 42)
                        .addComponent(labelDeskripsiTextfield)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelToleransi)
                        .addGap(199, 199, 199)
                        .addComponent(labelStandard)
                        .addGap(239, 239, 239))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(labelQty)
                        .addGap(36, 36, 36)
                        .addComponent(labelMin)
                        .addGap(42, 42, 42)
                        .addComponent(labelMax)
                        .addGap(40, 40, 40)
                        .addComponent(labelTemp)
                        .addGap(26, 26, 26)
                        .addComponent(labelRamPress)
                        .addGap(18, 18, 18)
                        .addComponent(labelRotorSpeed)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelToleransi)
                        .addComponent(kodeSpek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelKodeSpek))
                    .addComponent(labelStandard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMin)
                    .addComponent(labelMax)
                    .addComponent(labelTemp)
                    .addComponent(labelRamPress)
                    .addComponent(labelRotorSpeed)
                    .addComponent(labelQty)
                    .addComponent(labelDeskripsiTextfield)
                    .addComponent(labelCode)
                    .addComponent(labelIngclass)))
        );

        txtIngred.setBackground(new java.awt.Color(204, 204, 204));
        txtIngred.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtIngred.setForeground(new java.awt.Color(255, 255, 255));
        txtIngred.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tekton Pro Cond", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("TOTAL");

        txtQty.setBackground(new java.awt.Color(204, 204, 204));
        txtQty.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtQty.setForeground(new java.awt.Color(255, 255, 255));
        txtQty.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });

        txtMin.setBackground(new java.awt.Color(204, 204, 204));
        txtMin.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtMin.setForeground(new java.awt.Color(255, 255, 255));
        txtMin.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtMax.setBackground(new java.awt.Color(204, 204, 204));
        txtMax.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtMax.setForeground(new java.awt.Color(255, 255, 255));
        txtMax.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField136.setBackground(new java.awt.Color(204, 204, 204));
        jTextField136.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField136.setForeground(new java.awt.Color(255, 255, 255));
        jTextField136.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField137.setBackground(new java.awt.Color(204, 204, 204));
        jTextField137.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField137.setForeground(new java.awt.Color(255, 255, 255));
        jTextField137.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField138.setBackground(new java.awt.Color(204, 204, 204));
        jTextField138.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField138.setForeground(new java.awt.Color(255, 255, 255));
        jTextField138.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        panelTTD.setBackground(new java.awt.Color(0, 0, 0));

        txtTemp.setBackground(new java.awt.Color(204, 204, 204));
        txtTemp.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtTemp.setForeground(new java.awt.Color(255, 255, 255));
        txtTemp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRamPress.setBackground(new java.awt.Color(204, 204, 204));
        txtRamPress.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtRamPress.setForeground(new java.awt.Color(255, 255, 255));
        txtRamPress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtRotor.setBackground(new java.awt.Color(204, 204, 204));
        txtRotor.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtRotor.setForeground(new java.awt.Color(255, 255, 255));
        txtRotor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelTgl.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelTgl.setForeground(new java.awt.Color(255, 255, 255));
        labelTgl.setText("Tanggal Spec ");

        labelRevisi.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelRevisi.setForeground(new java.awt.Color(255, 255, 255));
        labelRevisi.setText("Revisi");

        txtTanggal.setBackground(new java.awt.Color(204, 204, 204));
        txtTanggal.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtTanggal.setForeground(new java.awt.Color(255, 255, 255));
        txtTanggal.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtRevisi.setBackground(new java.awt.Color(204, 204, 204));
        txtRevisi.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        txtRevisi.setForeground(new java.awt.Color(255, 255, 255));
        txtRevisi.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");

        chkStaff.setText("Staff WIP SPec");
        chkStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkStaffActionPerformed(evt);
            }
        });

        chkSH.setText("Section Head");
        chkSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSHActionPerformed(evt);
            }
        });

        chkADH.setText("Asst Dept Head");
        chkADH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkADHActionPerformed(evt);
            }
        });

        chkDH.setText("Dept Head");
        chkDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDHActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(ttdStaff);

        jScrollPane5.setViewportView(ttdStaff2);

        jScrollPane6.setViewportView(ttdSH);

        labelTtdSH.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelTtdSH.setForeground(new java.awt.Color(255, 255, 255));
        labelTtdSH.setText("Sect Head");

        labelTtdSH1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelTtdSH1.setForeground(new java.awt.Color(255, 255, 255));
        labelTtdSH1.setText("ADH");

        labelTtdSH2.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelTtdSH2.setForeground(new java.awt.Color(255, 255, 255));
        labelTtdSH2.setText("Staff WIP Spec");

        labelTtdSH3.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        labelTtdSH3.setForeground(new java.awt.Color(255, 255, 255));
        labelTtdSH3.setText("Dept Head");

        javax.swing.GroupLayout panelTTDLayout = new javax.swing.GroupLayout(panelTTD);
        panelTTD.setLayout(panelTTDLayout);
        panelTTDLayout.setHorizontalGroup(
            panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTDLayout.createSequentialGroup()
                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTTDLayout.createSequentialGroup()
                        .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTTDLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRamPress, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRotor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTTDLayout.createSequentialGroup()
                                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTTDLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelTTDLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(labelTtdSH2)))
                                .addGap(18, 18, 18)
                                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTtdSH))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelTTDLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(labelTtdSH1)))
                                .addGap(18, 18, 18)
                                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTtdSH3)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(panelTTDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTTDLayout.createSequentialGroup()
                                .addComponent(labelTgl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTanggal))
                            .addGroup(panelTTDLayout.createSequentialGroup()
                                .addComponent(labelRevisi)
                                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTTDLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addGroup(panelTTDLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(txtRevisi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(panelTTDLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chkStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkSH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkADH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelTTDLayout.setVerticalGroup(
            panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemp)
                    .addComponent(txtRamPress)
                    .addComponent(txtRotor))
                .addGap(56, 56, 56)
                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTgl)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRevisi)
                    .addComponent(txtRevisi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTTDLayout.createSequentialGroup()
                        .addComponent(labelTtdSH3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTTDLayout.createSequentialGroup()
                        .addComponent(chkStaff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkADH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkDH)
                        .addGap(12, 12, 12)
                        .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnEdit)
                            .addComponent(btnDelete))
                        .addGap(42, 42, 42)
                        .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTtdSH1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelTtdSH)
                                .addComponent(labelTtdSH2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(150, 150, 150))
        );

        btnAddInput.setText("Add");
        btnAddInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInputActionPerformed(evt);
            }
        });

        tblSpek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSpek);

        btnEditInput.setText("Edit");
        btnEditInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInputActionPerformed(evt);
            }
        });

        btnEditInput1.setText("Delete");
        btnEditInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInput1ActionPerformed(evt);
            }
        });

        btnClearInput.setText("Clear");
        btnClearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField136, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField137, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField138, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(comboIngClass, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIngred, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnAddInput, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(btnEditInput, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnClearInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelTTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIngred, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboIngClass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddInput)
                            .addComponent(btnEditInput)
                            .addComponent(btnEditInput1)
                            .addComponent(btnClearInput))
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField136, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField137, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField138, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 0));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tekton Pro Cond", 0, 21)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Proses Mixing");

        jLabel20.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel20.setText("Step 1");

        jLabel21.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel21.setText("Step 2");

        jLabel22.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel22.setText("Step 3");

        jLabel23.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel23.setText("Step 4");

        jLabel24.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel24.setText("Step 5");

        jLabel25.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel25.setText("Step 6");

        jPanel7.setBackground(new java.awt.Color(0, 255, 255));

        jTextField70.setBackground(new java.awt.Color(204, 204, 204));
        jTextField70.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField70.setForeground(new java.awt.Color(255, 255, 255));
        jTextField70.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField71.setBackground(new java.awt.Color(204, 204, 204));
        jTextField71.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField71.setForeground(new java.awt.Color(255, 255, 255));
        jTextField71.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField72.setBackground(new java.awt.Color(204, 204, 204));
        jTextField72.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField72.setForeground(new java.awt.Color(255, 255, 255));
        jTextField72.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField73.setBackground(new java.awt.Color(204, 204, 204));
        jTextField73.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField73.setForeground(new java.awt.Color(255, 255, 255));
        jTextField73.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField75.setBackground(new java.awt.Color(204, 204, 204));
        jTextField75.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField75.setForeground(new java.awt.Color(255, 255, 255));
        jTextField75.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField76.setBackground(new java.awt.Color(204, 204, 204));
        jTextField76.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField76.setForeground(new java.awt.Color(255, 255, 255));
        jTextField76.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField77.setBackground(new java.awt.Color(204, 204, 204));
        jTextField77.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField77.setForeground(new java.awt.Color(255, 255, 255));
        jTextField77.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField78.setBackground(new java.awt.Color(204, 204, 204));
        jTextField78.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField78.setForeground(new java.awt.Color(255, 255, 255));
        jTextField78.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField79.setBackground(new java.awt.Color(204, 204, 204));
        jTextField79.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField79.setForeground(new java.awt.Color(255, 255, 255));
        jTextField79.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField80.setBackground(new java.awt.Color(204, 204, 204));
        jTextField80.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField80.setForeground(new java.awt.Color(255, 255, 255));
        jTextField80.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField81.setBackground(new java.awt.Color(204, 204, 204));
        jTextField81.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField81.setForeground(new java.awt.Color(255, 255, 255));
        jTextField81.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField82.setBackground(new java.awt.Color(204, 204, 204));
        jTextField82.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField82.setForeground(new java.awt.Color(255, 255, 255));
        jTextField82.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField83.setBackground(new java.awt.Color(204, 204, 204));
        jTextField83.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField83.setForeground(new java.awt.Color(255, 255, 255));
        jTextField83.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField84.setBackground(new java.awt.Color(204, 204, 204));
        jTextField84.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField84.setForeground(new java.awt.Color(255, 255, 255));
        jTextField84.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField85.setBackground(new java.awt.Color(204, 204, 204));
        jTextField85.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField85.setForeground(new java.awt.Color(255, 255, 255));
        jTextField85.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField86.setBackground(new java.awt.Color(204, 204, 204));
        jTextField86.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField86.setForeground(new java.awt.Color(255, 255, 255));
        jTextField86.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField87.setBackground(new java.awt.Color(204, 204, 204));
        jTextField87.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField87.setForeground(new java.awt.Color(255, 255, 255));
        jTextField87.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField88.setBackground(new java.awt.Color(204, 204, 204));
        jTextField88.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField88.setForeground(new java.awt.Color(255, 255, 255));
        jTextField88.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField89.setBackground(new java.awt.Color(204, 204, 204));
        jTextField89.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField89.setForeground(new java.awt.Color(255, 255, 255));
        jTextField89.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField90.setBackground(new java.awt.Color(204, 204, 204));
        jTextField90.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField90.setForeground(new java.awt.Color(255, 255, 255));
        jTextField90.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField91.setBackground(new java.awt.Color(204, 204, 204));
        jTextField91.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField91.setForeground(new java.awt.Color(255, 255, 255));
        jTextField91.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField92.setBackground(new java.awt.Color(204, 204, 204));
        jTextField92.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField92.setForeground(new java.awt.Color(255, 255, 255));
        jTextField92.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField93.setBackground(new java.awt.Color(204, 204, 204));
        jTextField93.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField93.setForeground(new java.awt.Color(255, 255, 255));
        jTextField93.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField94.setBackground(new java.awt.Color(204, 204, 204));
        jTextField94.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField94.setForeground(new java.awt.Color(255, 255, 255));
        jTextField94.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField95.setBackground(new java.awt.Color(204, 204, 204));
        jTextField95.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField95.setForeground(new java.awt.Color(255, 255, 255));
        jTextField95.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField96.setBackground(new java.awt.Color(204, 204, 204));
        jTextField96.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField96.setForeground(new java.awt.Color(255, 255, 255));
        jTextField96.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField97.setBackground(new java.awt.Color(204, 204, 204));
        jTextField97.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField97.setForeground(new java.awt.Color(255, 255, 255));
        jTextField97.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField98.setBackground(new java.awt.Color(204, 204, 204));
        jTextField98.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField98.setForeground(new java.awt.Color(255, 255, 255));
        jTextField98.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jTextField99.setBackground(new java.awt.Color(204, 204, 204));
        jTextField99.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField99.setForeground(new java.awt.Color(255, 255, 255));
        jTextField99.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel27.setText("jLabel26");
        jLabel27.setOpaque(true);

        jLabel28.setText("jLabel26");
        jLabel28.setOpaque(true);

        jLabel29.setText("jLabel26");
        jLabel29.setOpaque(true);

        jLabel30.setText("jLabel26");
        jLabel30.setOpaque(true);

        jLabel31.setText("jLabel26");
        jLabel31.setOpaque(true);

        jTextField100.setBackground(new java.awt.Color(204, 204, 204));
        jTextField100.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextField100.setForeground(new java.awt.Color(255, 255, 255));
        jTextField100.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField100, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField79, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField83, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextField84, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField82, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField88, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField89, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField87, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField86, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField85, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField93, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField94, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField92, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField91, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField90, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField95, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField96, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField97, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField98, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField99, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField95, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField90, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField85, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField96, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField91, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField86, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField97, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField92, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField87, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField82, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField98, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField93, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField88, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField83, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField99, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField94, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField89, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField84, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jTextField79, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField100, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel21)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel22)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel23)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel24)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel25))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(labelCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(labelDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompound)
                    .addComponent(labelDeskripsi)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel17.setText("Mesin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(113, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel17)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearInputActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnClearInputActionPerformed

    private void btnEditInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditInput1ActionPerformed

    private void btnEditInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditInputActionPerformed

    private void btnAddInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInputActionPerformed
        // TODO add your handling code here:
        try{

            Statement statement=(Statement)Conek.GetConnection().createStatement();
            int result=statement.executeUpdate("INSERT INTO `tb_detail_spesifikasi` (`kode_DS`, `kode_S`, `kode_IS`, `kode_mt`, `qty`) VALUES "+

                "("+null+
                //                    "','"+tjab.getText()+
                "','"+comboIngClass.getSelectedItem()+
                "','"+txtCode.getText()+
                "','"+txtQty.getText()+"')");
            JOptionPane.showMessageDialog(rootPane,"Saving Success");

            txtCode.setText(null);
            txtIngred.setText(null);
            txtQty.setText(null);

            getData();
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Failed");
        }

    }//GEN-LAST:event_btnAddInputActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void chkDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDHActionPerformed

    private void chkADHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkADHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkADHActionPerformed

    private void chkSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSHActionPerformed

    private void chkStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkStaffActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            Connection conek = Conek.GetConnection();
            Statement statement = conek.createStatement();
            //        int result = statement.executeUpdate("insert into tb_spesifikasi values "
                //                + "('" + tkode.getText()
                //                + "','" + tlok.getText()
                //                + "','" + tkap.getText() + "')");
            JOptionPane.showMessageDialog(rootPane, "Berhasil Simpan");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Gagal simpan");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_spesifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_spesifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_spesifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_spesifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new form_spesifikasi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInput;
    private javax.swing.JButton btnClearInput;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditInput;
    private javax.swing.JButton btnEditInput1;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkADH;
    private javax.swing.JCheckBox chkDH;
    private javax.swing.JCheckBox chkSH;
    private javax.swing.JCheckBox chkStaff;
    private javax.swing.JComboBox comboIngClass;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField100;
    private javax.swing.JTextField jTextField136;
    private javax.swing.JTextField jTextField137;
    private javax.swing.JTextField jTextField138;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField87;
    private javax.swing.JTextField jTextField88;
    private javax.swing.JTextField jTextField89;
    private javax.swing.JTextField jTextField90;
    private javax.swing.JTextField jTextField91;
    private javax.swing.JTextField jTextField92;
    private javax.swing.JTextField jTextField93;
    private javax.swing.JTextField jTextField94;
    private javax.swing.JTextField jTextField95;
    private javax.swing.JTextField jTextField96;
    private javax.swing.JTextField jTextField97;
    private javax.swing.JTextField jTextField98;
    private javax.swing.JTextField jTextField99;
    private javax.swing.JTextField kodeSpek;
    private javax.swing.JLabel labelCode;
    private javax.swing.JLabel labelCompound;
    private javax.swing.JLabel labelDeskripsi;
    private javax.swing.JLabel labelDeskripsiTextfield;
    private javax.swing.JLabel labelIngclass;
    private javax.swing.JLabel labelKodeSpek;
    private javax.swing.JLabel labelMax;
    private javax.swing.JLabel labelMin;
    private javax.swing.JLabel labelQty;
    private javax.swing.JLabel labelRamPress;
    private javax.swing.JLabel labelRevisi;
    private javax.swing.JLabel labelRotorSpeed;
    private javax.swing.JLabel labelStandard;
    private javax.swing.JLabel labelTemp;
    private javax.swing.JLabel labelTgl;
    private javax.swing.JLabel labelToleransi;
    private javax.swing.JLabel labelTtdSH;
    private javax.swing.JLabel labelTtdSH1;
    private javax.swing.JLabel labelTtdSH2;
    private javax.swing.JLabel labelTtdSH3;
    private javax.swing.JPanel panelTTD;
    private javax.swing.JTable tblSpek;
    private javax.swing.JTextPane ttdSH;
    private javax.swing.JTextPane ttdStaff;
    private javax.swing.JTextPane ttdStaff2;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtIngred;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtRamPress;
    private javax.swing.JTextField txtRevisi;
    private javax.swing.JTextField txtRotor;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables

    private static class Item {

        private int id;
        private String name;

        public Item(int id, String name) {
            this.id = id;
            this.name = name;
        }

        public int getId() {
            return id;
        }

        public String getName() {
            return name;
        }
    }
}
